# Generated by Django 3.1.3 on 2021-02-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210204_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now=True)),
                ('postedBy', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
